---

- name: Upload gcp credentials
  ansible.builtin.copy:
    src: "whanos_gcp_creds.json"
    dest: /var/lib/jenkins/whanos_gcp_creds.json
    mode: preserve
  become: true

- name: Zip docker images folder
  community.general.archive:
    path: "{{ playbook_dir }}/jenkins/files/docker_images"
    dest: docker_images.zip
    format: zip
    mode: 0600
  delegate_to: localhost
  become: false

- name: Zip scripts folder
  community.general.archive:
    path: "{{ playbook_dir }}/jenkins/files/scripts"
    dest: scripts.zip
    format: zip
    mode: 0600
  delegate_to: localhost
  become: false

- name: Upload docker images
  ansible.builtin.unarchive:
    src: docker_images.zip
    dest: /var/lib/jenkins
  become: true

- name: Upload scripts
  ansible.builtin.unarchive:
    src: scripts.zip
    dest: /var/lib/jenkins
  become: true

- name: Download docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/docker_install.sh
    mode: 0755

- name: Install docker
  ansible.builtin.command:
    cmd: /tmp/docker_install.sh
    creates: /usr/bin/docker
  changed_when: false
  become: true

- name: Download helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/helm_install.sh
    mode: 0755

- name: Install helm
  ansible.builtin.command:
    cmd: /tmp/helm_install.sh
    creates: /usr/bin/helm
  changed_when: false
  become: true

- name: Download kubectl install script
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    mode: 0755
  changed_when: false

- name: Install kubectl
  ansible.builtin.command:
    cmd: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    creates: /usr/local/bin/kubectl
  changed_when: false
  become: true
