FROM node:14.17.5-alpine3.14@sha256:572619bd5534df6a4330126cd4ad3fcfeaa7e53e4dfd0c42a6762f29c8de7084

SHELL ["/bin/bash", "-c"]

RUN npm install befunge93@^1.0.5

RUN wget https://github.com/TEAM-AAAAAAAAAAAAAAAA/Whanos/raw/main/images/befunge/b93.js

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD CMD [ "node", "b93.js", "app/main.bf"]
