FROM maven:3.8-openjdk-17-slim@sha256:502e781d39f0b40fbd02eb23f5b7663618b76ba52034da218c64e92f6c5647be

ONBUILD COPY . /app

WORKDIR /app

ONBUILD RUN mvn dependency:resolve -f app/pom.xml

ONBUILD RUN mvn package -f app/pom.xml

ONBUILD RUN app/target/app.jar .

ONBUILD RUN rm -rf app/

FROM openjdk:8-jre-alpine@sha256:f362b165b870ef129cbe730f29065ff37399c0aa8bcab3e44b51c302938c9193

# ONBUILD CMD ["java", "-jar", "app.jar"]
