FROM maven:3.8-openjdk-17-slim@sha256:502e781d39f0b40fbd02eb23f5b7663618b76ba52034da218c64e92f6c5647be as builder

SHELL ["/bin/bash", "-c"]

COPY . /app

WORKDIR /app

RUN mvn dependency:resolve -f app/pom.xml && mvn package -f app/pom.xml && app/target/app.jar . && rm -rf app/

FROM openjdk:8-jre-alpine

COPY --from=builder /app /app

WORKDIR /app

# CMD [ "java", "-jar", "app.jar" ]
