---
# vars file for jenkins

# General variables
java_version: "default-jre"

# GCP variables
gcp:
  project_id: "nomadic-mesh-376709"
  project_user: "whanos"
  project_region: "europe-west4"
  creds: "/var/lib/jenkins/whanos_gcp_creds.json"
  gcloud_apt_key: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xB53DC80D13EDEF05"
  gcloud_apt_repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"

# Jenkins variables
jenkins:
  jenkins_key: "https://pkg.jenkins.io/debian/jenkins.io.key"
  jenkins_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
