---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  name: {{ .Release.Name }}-deploy_build
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    spec:
#        - name: {{ .Chart.Name }}
#          securityContext:
#            {{- toYaml .Values.securityContext | nindent 12 }}
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: {{ .Values.service.port }}
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
#          resources:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.image }}
        {{- if .Values.deploy_build.resources }}
        resources: {{ .Values.deploy_build.resources | toJson }}
        {{- end }}
        {{- if .Values.deploy_build.ports }}
        ports:
          {{- range .Values.deploy_build.ports }}
          - containerPort: {{ . }}
          {{- end }}
        {{- end }}
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
  replicas: {{ .Values.deploy_build.replicas }}

{{- if .Values.deploy_build.ports }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
spec:
  type: LoadBalancer
  ports:
    {{- range .Values.deploy_build.ports }}
    - targetPort: {{ . }}
      protocol: TCP
      port: {{ . }}
      name: {{ . | quote }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
