---

{{- $release := .Release.Name -}}
{{- $resources := .Values.deploybuild.resources -}}
{{- $ports := .Values.deploybuild.ports -}}
{{- $replicas := .Values.deploybuild.replicas -}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  name: {{ $release }}-deploybuild
spec:
  selector:
    matchLabels:
      app: {{ $release }}
  template:
    spec:
{{- /*
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
*/}}
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.image }}
        {{- if $resources }}
        resources: {{ $resources | toJson }}
        {{- end }}
        {{- if $ports }}
        ports:
          {{- range $ports }}
          - containerPort: {{ . }}
          {{- end }}
        {{- end }}
    metadata:
      labels:
        app: {{ $release }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
  replicas: {{ $replicas }}

{{- if $ports }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $release }}-loadbalancer
spec:
  type: LoadBalancer
  ports:
    {{- range $ports }}
    - targetPort: {{ . }}
      protocol: TCP
      port: {{ . }}
      name: {{ . | quote }}
    {{- end }}
  selector:
    app: {{ $release }}

{{- end }}
