---
- name: Deploy jenkins
  hosts: jenkins
  environment:
    USER_ADMIN_PASSWORD: paul
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  become: true
  tasks:
    - name: Upload scripts
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../scripts"
        dest: "/"
        mode: "preserve"

    # - name: Install Jenkins
    #   ansible.builtin.shell: "/install-jenkins.sh"
    # #  become_user: root
    #   become: true
    #   changed_when: false

    - name: Upload Docker images
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../images"
        dest: /var/lib/jenkins
        mode: preserve
    #  become_user: root
      become: true
    #  register:
    #  when: install_postgres_server

    - name: Upload jobs.groovy
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../jenkins/jobs/"
        dest: /var/lib/jenkins
        mode: preserve

    # - name: Upload jcasc
    #   ansible.builtin.copy:
    #     src: "{{ playbook_dir }}/../jenkins/jenkins.yml"
    #     dest: /var/lib/jenkins
    #     mode: preserve

    - name: Install Docker
      ansible.builtin.shell: /scripts/install-docker.sh

    - name: Install Helm
      ansible.builtin.shell: "/scripts/install-helm.sh"

    - name: Restart jenkins
      ansible.builtin.service:
        name: jenkins
        state: restarted

  # - name: Restart postgresql service
  #   service:
  #     name: postgresql
  #     state: restarted

  # - name: Create db user
  #   postgresql_user:
  #     name: paul
  #     password: "{{ db_password }}"
  #     state: present
  #   become: true
  #   become_user: postgres
