FROM node:14.17.5-alpine3.14@sha256:572619bd5534df6a4330126cd4ad3fcfeaa7e53e4dfd0c42a6762f29c8de7084

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD RUN npm install dependencies --production=false

ONBUILD EXPOSE 3000

ONBUILD CMD ["node", "."]